public with sharing class PRClassTwo {
    public PRClassTwo() {

    }

    public static void deployDeltaChangeOnly(){
        System.debug('PR ClassTwo Method');
    }

    public static void deployDeltaChangeOnlyTwo(){
        System.debug('PR ClassTwo Method One more');
    }

    public static void deployDeltaChangeOnlyTwoThree(){
        System.debug('PR ClassTwo Method Two more');
    }
}
